# Generated by Django 3.2.7 on 2021-09-20 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_carro', models.CharField(max_length=9)),
                ('modelo_carro', models.CharField(max_length=100)),
                ('cor_do_carro', models.CharField(max_length=100)),
                ('entrada', models.DateTimeField(default=datetime.datetime.now)),
                ('saida', models.DateTimeField(default=datetime.datetime.now)),
                ('parking_time', models.DurationField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
